services:
  mongodb:
    image: mongo:5.0.15
    environment:
      - MONGO_INITDB_ROOT_USERNAME:buithanhhuy104
      - MONGO_INITDB_ROOT_PASSWORD:huy123456789
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: